site_name: Dark Water Documentation
pages:
- Overview: index.md
- About: about.md
theme: readthedocs
repo_name: 'GitHub'
repo_url: "https://github.com/darkwaterfoundation/docs"
extra:
  palette:
    primary: 'blue grey'
    accent: 'light blue'
  author:
    github: 'darkwaterfoundation'
    twitter: 'darkwaterio'